---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     or SHA make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.

### Default values for variables in this file are:
## openstack_opendev_base_url: https://opendev.org
## openstack_github_base_url: https://github.com

### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.

### HEAD as of 02.03.2023 ###

## Global Requirements
requirements_git_repo: "{{ openstack_opendev_base_url }}/openstack/requirements"
requirements_git_install_branch: 4eb31299dcd912d55ec659319237bb4389ba12f1
requirements_git_track_branch: master

## Adjutant service
adjutant_git_repo: "{{ openstack_opendev_base_url }}/openstack/adjutant"
adjutant_git_install_branch: df8c3e4a8b70be8697ac46f0acec9169752b4698
adjutant_git_track_branch: master

## Adjutant dashboard plugin
adjutant_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/adjutant-ui"
adjutant_dashboard_git_install_branch: 6fa9478b154ba07e4c70aba6c8fa6cc65450fb42
adjutant_dashboard_git_track_branch: master

## Aodh service
aodh_git_repo: "{{ openstack_opendev_base_url }}/openstack/aodh"
aodh_git_install_branch: aa91a3b6141dd3177d581c5517ae9fe37e75ab4c
aodh_git_track_branch: master

## Barbican service
barbican_git_repo: "{{ openstack_opendev_base_url }}/openstack/barbican"
barbican_git_install_branch: d318b9b99d83538c9897605db22af35c5866b0f0
barbican_git_track_branch: master

## Barbican dashboard plugin
barbican_dashboard_git_repo: "{{ openstack_opendev_base_url }}//openstack/barbican-ui"
barbican_dashboard_git_install_branch: 3a78a743426376250f43508d4281e86c75067271
barbican_dashboard_git_track_branch: master

## Ceilometer service
ceilometer_git_repo: "{{ openstack_opendev_base_url }}/openstack/ceilometer"
ceilometer_git_install_branch: ccce41555008fcffc941c91d1d1090be6611a57e
ceilometer_git_track_branch: master

## Cinder service
cinder_git_repo: "{{ openstack_opendev_base_url }}/openstack/cinder"
cinder_git_install_branch: a53ff6727a42a7730e27772b64cfd511194721e1
cinder_git_track_branch: master

## Cloudkitty service
cloudkitty_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty"
cloudkitty_git_install_branch: 73d5543f15ec188fafa1562f4142edd41afbad5c
cloudkitty_git_track_branch: master

## Cloudkitty dashboard plugin
cloudkitty_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/cloudkitty-dashboard"
cloudkitty_dashboard_git_install_branch: 7cdee86bac20a38d191677eaefe94914cc5207f7
cloudkitty_dashboard_git_track_branch: master

## Designate service
designate_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate"
designate_git_install_branch: 8910a2014be52808cb3f4a42953b2176e852d0ad
designate_git_track_branch: master

## Horizon Designate dashboard plugin
designate_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/designate-dashboard"
designate_dashboard_git_install_branch: 2468623f1b0dde2385f27505113b8ec51f7e6c28
designate_dashboard_git_track_branch: master

## Glance service
glance_git_repo: "{{ openstack_opendev_base_url }}/openstack/glance"
glance_git_install_branch: f0371614d5093463ede1b846227db6473f9ece82
glance_git_track_branch: master

## Heat service
heat_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat"
heat_git_install_branch: 3ab94722750f71b36f702badb2ea7ed176d4c22c
heat_git_track_branch: master

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/heat-dashboard"
heat_dashboard_git_install_branch: fa9efec740b54cf05f6607098a4fbf13e5e58f8b
heat_dashboard_git_track_branch: master

## Horizon service
horizon_git_repo: "{{ openstack_opendev_base_url }}/openstack/horizon"
horizon_git_install_branch: d4b73ed1c415da84db2a67f2d24f465b604e1359
horizon_git_track_branch: master

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: "{{ openstack_opendev_base_url}}/openstack/ironic-ui"
ironic_dashboard_git_install_branch: 676aef6bbfe886cfbc8f8cc617cd8a271b8e85b2
ironic_dashboard_git_track_branch: master

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum-ui"
magnum_dashboard_git_install_branch: 452ca7da23f4489bc0dd25cfd031d4f1db04dfa6
magnum_dashboard_git_track_branch: master

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-dashboard"
masakari_dashboard_git_install_branch: c1928878d0fefa79a080aeb34693b629f9f822fb
masakari_dashboard_git_track_branch: master

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/sahara-dashboard"
sahara_dashboard_git_install_branch: 2fbedc589de71681cb2010c6534fba13529047aa
sahara_dashboard_git_track_branch: master

## Keystone service
keystone_git_repo: "{{ openstack_opendev_base_url }}/openstack/keystone"
keystone_git_install_branch: 909fe93fb15358c43420778d936b5648b96f9456
keystone_git_track_branch: master

## Manila service
manila_git_repo: "{{ openstack_opendev_base_url }}/openstack/manila"
manila_git_install_branch: 51f75da64eb4878de9c656032790e4ed3579a3b8
manila_git_track_branch: master

## Neutron service
neutron_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron"
neutron_git_install_branch: 92766c85b642bdece24c629625bf80050882c797
neutron_git_track_branch: master

neutron_vpnaas_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-vpnaas"
neutron_vpnaas_git_install_branch: 792f2c65ec34b63ae8037a5328b7622320c4e1c4
neutron_vpnaas_git_track_branch: master


neutron_dynamic_routing_git_repo: "{{ openstack_opendev_base_url }}/openstack/neutron-dynamic-routing"
neutron_dynamic_routing_git_install_branch: d41c3f0749c12c28c4004b8a58a6d11cf9394dc1
neutron_dynamic_routing_git_track_branch: master

networking_odl_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-odl"
networking_odl_git_install_branch: d8316e6f531e7568fdb9dca6fae89902eb566c40
networking_odl_git_track_branch: master

networking_bgpvpn_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-bgpvpn"
networking_bgpvpn_git_install_branch: 902b82169db078bcd3765ce1115c11ab872c72a6
networking_bgpvpn_git_track_branch: master

networking_sfc_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-sfc"
networking_sfc_git_install_branch: f9fb840b72b87d67790d34d637f6b47d9ca93f7d
networking_sfc_git_track_branch: master

networking_generic_switch_git_repo: "{{ openstack_opendev_base_url}}/openstack/networking-generic-switch"
networking_generic_switch_git_install_branch: 1b715fd5cf387e186594417b30d17d5cfcd97ae7
networking_generic_switch_git_track_branch: master

networking_nsx_git_repo: "{{ openstack_opendev_base_url }}/x/vmware-nsx"
networking_nsx_git_install_branch: 0253265f75f63d5619b30f16a6b64459dec79d82
networking_nsx_git_track_branch: master

networking_nsxlib_git_repo: "{{ openstack_opendev_base_url }}/x/vmware-nsxlib"
networking_nsxlib_git_install_branch: d049dbc406adfb99e493d6cefaf71fa61064592e
networking_nsxlib_git_track_branch: master

networking_baremetal_git_repo: "{{ openstack_opendev_base_url }}/openstack/networking-baremetal"
networking_baremetal_git_install_branch: 2cf7c04d7799f17e2d6f7ead0ecaa9c0e8426ad5
networking_baremetal_git_track_branch: master

## Nova service
nova_git_repo: "{{ openstack_opendev_base_url }}/openstack/nova"
nova_git_install_branch: 6b0b009783770354f9387ae4d2d99fca05fb5acd
nova_git_track_branch: master

## Sahara service
sahara_git_repo: "{{ openstack_opendev_base_url }}/openstack/sahara"
sahara_git_install_branch: 5e7258bcc8807493f08671be9b8f4f4c4232eb0a
sahara_git_track_branch: master

## Senlin service
senlin_git_repo: "{{ openstack_opendev_base_url }}/openstack/senlin"
senlin_git_install_branch: d76152595f0fdd8bd69fe6e6336b1777d3365509
senlin_git_track_branch: master

## Swift service
swift_git_repo: "{{ openstack_opendev_base_url }}/openstack/swift"
swift_git_install_branch: 2a90eadc0d20cef9833a0e7737f5c36becf46b3b
swift_git_track_branch: master

## Ironic service
ironic_git_repo: "{{ openstack_opendev_base_url }}/openstack/ironic"
ironic_git_install_branch: 63de82c3d3724d7989ffe119cc78d2aa9399aa77
ironic_git_track_branch: master

## Ironic inspector service
ironic_inspector_git_repo: "{{ openstack_opendev_base_url }}/openstack/ironic-inspector"
ironic_inspector_git_install_branch: 836ba11b9bc83232ffd8ee91b0a727216aa0861a
ironic_inspector_git_track_branch: master

## Magnum service
magnum_git_repo: "{{ openstack_opendev_base_url }}/openstack/magnum"
magnum_git_install_branch: ab9fe94d5333edc6d269f7fe2b1cd32fe4a98d3a
magnum_git_track_branch: master

## Masakari service
masakari_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari"
masakari_git_install_branch: 3e1b85133a59ee68a3b18e47e7dc49ab30097e63
masakari_git_track_branch: master

## Masakari monitors services
masakari_monitors_git_repo: "{{ openstack_opendev_base_url }}/openstack/masakari-monitors"
masakari_monitors_git_install_branch: cf646dfce2db86f01dd49349e1803da23de4ec85
masakari_monitors_git_track_branch: master

## Mistral service
mistral_git_repo: "{{ openstack_opendev_base_url }}/openstack/mistral"
mistral_git_install_branch: 4289317a914cd2542a23ccc2f3cdcb0d7fd00676
mistral_git_track_branch: master

mistral_extra_git_repo: "{{ openstack_opendev_base_url }}/openstack/mistral-extra"
mistral_extra_git_install_branch: e0687d607319b796503859353b8f3ab1cc9aa9f5
mistral_extra_git_track_branch: master

## Murano service
murano_git_repo: "{{ openstack_opendev_base_url }}/openstack/murano"
murano_git_install_branch: ada28b3ac6e6c19688dc6fd6a19630d1cf5e0530
murano_git_track_branch: master

murano_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/murano-dashboard"
murano_dashboard_git_install_branch: 5e73220a5f81adb9b59ab0711fecad23ddfd5a1b
murano_dashboard_git_track_branch: master

## Trove service
trove_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove"
trove_git_install_branch: 2fbbb09d22039f672ef4a084617bff8748fba134
trove_git_track_branch: master

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/trove-dashboard"
trove_dashboard_git_install_branch: 8309206de77a2079193f64fb29669b2ef5594a46
trove_dashboard_git_track_branch: master

## Octavia service
octavia_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia"
octavia_git_install_branch: 3475a4b3c2b0614d4a6f1e51d6b08d3abcc5f7ca
octavia_git_track_branch: master

## Octavia OVN provider
octavia_ovn_octavia_provider_git_repo: "{{ openstack_opendev_base_url }}/openstack/ovn-octavia-provider"
octavia_ovn_octavia_provider_git_install_branch: 569c9c011a2cc9e5f041633dde4a47257e4d8565
octavia_ovn_octavia_provider_git_track_branch: master

## Placement service
placement_git_repo: "{{ openstack_opendev_base_url }}/openstack/placement"
placement_git_install_branch: 9fa635bd60cff51effc7ae65e8562664ce7ce24c
placement_git_track_branch: master

## Tacker service
tacker_git_repo: "{{ openstack_opendev_base_url }}/openstack/tacker"
tacker_git_install_branch: d457da69d96bfe0c3586abfb59797d51462a5806
tacker_git_track_branch: master

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: "{{ openstack_opendev_base_url }}/openstack/octavia-dashboard"
octavia_dashboard_git_install_branch: d6bf1ed92d5d759414115e4ae010710666ea7751
octavia_dashboard_git_track_branch: master

## Blazar service
blazar_git_repo: "{{ openstack_opendev_base_url }}/openstack/blazar"
blazar_git_install_branch: af4e4490dd880b152e4ea4ff0395b8b7d88627ca
blazar_git_track_branch: master

## Blazar Nova Service
blazar_nova_git_repo: "{{ openstack_opendev_base_url }}/openstack/blazar-nova"
blazar_nova_git_install_branch: 5579fb4728187e9bd3ffce2b396ea98c65fc9b42
blazar_nova_git_track_branch: master

## Zun service
zun_git_repo: "{{ openstack_opendev_base_url }}/openstack/zun"
zun_git_install_branch: c43f423530d32f6ac0c245b996642e7503b6b043
zun_git_track_branch: master

## Zun kuryr service
zun_kuryr_git_repo: "{{ openstack_opendev_base_url }}/openstack/kuryr-libnetwork"
zun_kuryr_git_install_branch: 7fce4cd9251f29ede3659b41a8cbd099134be29f
zun_kuryr_git_track_branch: master

## Zun kuryr library
zun_kuryr_lib_git_repo: "{{ openstack_opendev_base_url }}/openstack/kuryr"
zun_kuryr_lib_git_install_branch: deaf2f4f810afda8bb7fd8e6cd99be9a8b1ab264
zun_kuryr_lib_git_track_branch: master
